title: "Replication Team"
description: "We replicate open source labratory hardware. Our goal is to document, audit, and contibute to open source projects. All materials, code, and results are publicly available."
url: ""
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
